update directory check

diff --git a/.github/workflows/test-container-workflow.yml b/.github/workflows/test-container-workflow.yml
--- a/.github/workflows/test-container-workflow.yml
+++ b/.github/workflows/test-container-workflow.yml
@@ -15,4 +15,5 @@ jobs:
         - name: Run Tests on Image
           run: docker run --entrypoint '/app/test.sh' -v $PWD/sample-data/:/data shape2open:test 
         - name: Check Test Files
-          run: ls -la sample-data/
+          run: [ -d "sample-data/" ] && echo "Directory sample-data/ exists." || echo "Error: Directory sample-data/ does not exists."
+
